services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    command: daphne -b 0.0.0.0 -p 8000 chat_app.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: whatsapp_clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: guirgis
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: